package stringcensus

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// Generated file names inside Options.OutDir.
const (
	GoOnlyFile     = "go-only.tsv"
	CMissingFile   = "c-missing.tsv"
	UnresolvedFile = "go-unresolved.tsv"
	SummaryFile    = "summary.txt"
)

// header is the provenance comment every generated report carries.
const header = "# Generated by cmd/dp-string-census (make string-census-update). Do not edit by hand.\n"

// GoOnlyTexts returns the distinct go-only segment texts, sorted. It is the
// ratchet's key set.
func (r *Report) GoOnlyTexts() []string {
	return uniqueTexts(r.GoOnlySegments)
}

// Render returns the generated reports keyed by file name. Tests and the CLI
// share it so the golden fixture and the checked-in reports cannot drift.
func (r *Report) Render() map[string]string {
	return map[string]string{
		GoOnlyFile:     r.goOnlyTSV(),
		CMissingFile:   r.cMissingTSV(),
		UnresolvedFile: r.unresolvedTSV(),
		SummaryFile:    r.summary(),
	}
}

// WriteOutputs writes the generated reports into outDir (an absolute path).
func (r *Report) WriteOutputs(outDir string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	for name, body := range r.Render() {
		p := filepath.Join(outDir, name)
		if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func (r *Report) goOnlyTSV() string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("# Go player-facing segments with no C source and no world-data source (R4 review queue).\n")
	b.WriteString("# columns: segment\tfile:line\tsink\n")
	for _, s := range r.GoOnlySegments {
		fmt.Fprintf(&b, "%s\t%s\t%s\n", sanitize(s.Text), site(s), s.Sink)
	}
	return b.String()
}

func (r *Report) cMissingTSV() string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("# C player-facing segments no Go segment contains (port gaps).\n")
	b.WriteString("# columns: segment\tfile:line\tsink\tfunction\n")
	for _, s := range r.CMissingSegments {
		fmt.Fprintf(&b, "%s\t%s\t%s\t%s\n", sanitize(s.Text), site(s), s.Sink, s.Fn)
	}
	return b.String()
}

func (r *Report) unresolvedTSV() string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("# Go sink arguments whose value the extractor could not resolve to literals.\n")
	b.WriteString("# Leads for tightening the sink table, not ratchet failures.\n")
	b.WriteString("# columns: expression\tfile:line\tsink\n")
	for _, u := range r.UnresolvedSites {
		fmt.Fprintf(&b, "%s\t%s:%d\t%s\n", sanitize(u.Expr), u.File, u.Line, u.Sink)
	}
	return b.String()
}

func (r *Report) summary() string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("# Deterministic: no dates, no paths outside the repository.\n")
	fmt.Fprintf(&b, "go files scanned\t%d\n", r.GoFiles)
	fmt.Fprintf(&b, "c files scanned\t%d\n", r.CFiles)
	fmt.Fprintf(&b, "data files scanned\t%d\n", r.DataFiles)
	fmt.Fprintf(&b, "go candidates (literal at a sink)\t%d\n", r.GoCandidates)
	fmt.Fprintf(&b, "c candidates (literal in a sink call)\t%d\n", r.CCandidates)
	fmt.Fprintf(&b, "go segments\t%d\n", r.GoSegmentCount)
	fmt.Fprintf(&b, "c segments\t%d\n", r.CSegmentCount)
	fmt.Fprintf(&b, "go-only segments\t%d\n", r.GoOnly)
	fmt.Fprintf(&b, "c-missing segments\t%d\n", r.CMissing)
	fmt.Fprintf(&b, "data-sourced segments\t%d\n", r.DataSourced)
	fmt.Fprintf(&b, "unresolved go sink arguments\t%d\n", len(r.UnresolvedSites))

	b.WriteString("\n[go sink table]\n")
	for _, name := range sortedGoSinkNames() {
		why := ""
		for _, s := range goSinks {
			if s.Name == name {
				why = s.Why
				break
			}
		}
		fmt.Fprintf(&b, "%s\t%d\t%s\n", name, r.goSinkCounts[name], why)
	}
	b.WriteString("\n[c sink table]\n")
	cNames := make([]string, 0, len(cSinks))
	for _, s := range cSinks {
		cNames = append(cNames, s.Name)
	}
	sort.Strings(cNames)
	for _, name := range cNames {
		why := ""
		for _, s := range cSinks {
			if s.Name == name {
				why = s.Why
				break
			}
		}
		fmt.Fprintf(&b, "%s\t%d\t%s\n", name, r.cSinkCounts[name], why)
	}

	b.WriteString("\n[go candidates by package]\n")
	writeCounts(&b, r.goPkgCounts)
	b.WriteString("\n[c candidates by file]\n")
	writeCounts(&b, r.cFileCounts)
	b.WriteString("\n[go-only segments by file]\n")
	writeCounts(&b, r.goOnlyByFile)
	b.WriteString("\n[c-missing segments by c file]\n")
	writeCounts(&b, r.cMissingByFile)
	return b.String()
}

// FileGroup is one file with its reported-segment count.
type FileGroup struct {
	File  string
	Count int
}

// GoOnlyByFile returns the go-only segment counts per file, largest first and
// ties broken by path so the order is deterministic.
func (r *Report) GoOnlyByFile() []FileGroup {
	return sortGroups(r.goOnlyByFile)
}

func sortGroups(counts map[string]int) []FileGroup {
	out := make([]FileGroup, 0, len(counts))
	for file, count := range counts {
		out = append(out, FileGroup{File: file, Count: count})
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].Count != out[j].Count {
			return out[i].Count > out[j].Count
		}
		return out[i].File < out[j].File
	})
	return out
}

// StaleOutputs names the generated reports whose on-disk copy differs from the
// current run. Check mode warns rather than fails: a fix that removes a string
// should not have to regenerate every report to pass.
func (r *Report) StaleOutputs(outDir string) ([]string, error) {
	generated := r.Render()
	var stale []string
	for name, want := range generated {
		got, err := os.ReadFile(filepath.Join(outDir, name)) // #nosec G304 -- name is one of the four constants above
		if err != nil || string(got) != want {
			stale = append(stale, name)
		}
	}
	return stale, nil
}

// writeCounts writes one count per line, sorted by key.
func writeCounts(b *strings.Builder, counts map[string]int) {
	keys := make([]string, 0, len(counts))
	for k := range counts {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(b, "%s\t%s\n", k, strconv.Itoa(counts[k]))
	}
}

// site renders the file:line column.
func site(s Segment) string { return s.File + ":" + strconv.Itoa(s.Line) }

// sanitize keeps a segment on one TSV line; normalized segments carry no tabs,
// but a foreign literal (an unquoted Go raw string, say) could.
func sanitize(s string) string {
	s = strings.ReplaceAll(s, "\t", " ")
	return strings.ReplaceAll(s, "\n", " ")
}
