package censuscoverage

import (
	"sort"

	"github.com/zax0rz/darkpawns/internal/stringcensus"
)

// Generated file names, matching the census's output directory.
const (
	CoverageFile = "coverage.tsv"
	SummaryFile  = "coverage-summary.txt"
)

// header is the provenance comment every generated report carries.
const header = "# Generated by cmd/dp-census-coverage (make census-coverage). Do not edit by hand.\n"

// Rollup is coverage for one C file or one C function.
type Rollup struct {
	Key             string
	Sites           int
	SitesCovered    int
	Segments        int
	SegmentsCovered int
	Unverifiable    int
	NeverSeen       []NeverSeenSegment
}

// NeverSeenSegment is one C segment no scenario printed.
type NeverSeenSegment struct {
	File string
	Line int
	Sink string
	Fn   string
	Text string
}

// ByFile groups the report by C source file.
func (r *Report) ByFile() []Rollup {
	return r.rollup(func(s stringcensus.CSite) string { return s.File })
}

// ByFunction groups the report by enclosing C function, keyed as
// "file:function" because a static helper name can repeat across files. The
// literals that sit outside any function (string tables) are keyed
// "file:<none>".
func (r *Report) ByFunction() []Rollup {
	return r.rollup(func(s stringcensus.CSite) string {
		fn := s.Fn
		if fn == "" {
			fn = "<none>"
		}
		return s.File + ":" + fn
	})
}

func (r *Report) rollup(key func(stringcensus.CSite) string) []Rollup {
	index := map[string]int{}
	var out []Rollup
	for i := range r.Sites {
		sc := &r.Sites[i]
		k := key(sc.Site)
		idx, ok := index[k]
		if !ok {
			idx = len(out)
			index[k] = idx
			out = append(out, Rollup{Key: k})
		}
		roll := &out[idx]
		roll.Sites++
		if sc.Covered() {
			roll.SitesCovered++
		}
		for _, seg := range sc.Site.Segments {
			roll.Segments++
			if sc.Covered() {
				roll.SegmentsCovered++
				continue
			}
			roll.NeverSeen = append(roll.NeverSeen, NeverSeenSegment{
				File: sc.Site.File, Line: sc.Site.Line, Sink: sc.Site.Sink, Fn: sc.Site.Fn, Text: seg,
			})
		}
		if sc.Site.Unverifiable() {
			roll.Unverifiable++
		}
	}
	for i := range out {
		misses := out[i].NeverSeen
		sort.Slice(misses, func(a, b int) bool {
			if misses[a].File != misses[b].File {
				return misses[a].File < misses[b].File
			}
			if misses[a].Line != misses[b].Line {
				return misses[a].Line < misses[b].Line
			}
			return misses[a].Text < misses[b].Text
		})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Key < out[j].Key })
	return out
}
