// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package config

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/pelletier/go-toml/v2"
)

type Config struct {
	BaseURL       string            `toml:"base_url"`
	BasePath      string            `toml:"base_path"`
	AuthHeaderVal string            `toml:"auth_header"`
	Headers       map[string]string `toml:"headers,omitempty"`
	AuthSource    string            `toml:"-"`
	Path          string            `toml:"-"`
}

func Load(configPath string) (*Config, error) {
	cfg := &Config{
		BasePath: "ws:/192.168.1.15:4350/ws",
	}

	// Resolve config path
	path := configPath
	if path == "" {
		path = os.Getenv("DP_GOAT_CONFIG")
	}
	if path == "" {
		home, _ := os.UserHomeDir()
		path = filepath.Join(home, ".config", "dp-goat-pp-cli", "config.toml")
	}
	cfg.Path = path

	// Try to load config file
	data, err := os.ReadFile(path)
	if err == nil {
		if err := toml.Unmarshal(data, cfg); err != nil {
			return nil, fmt.Errorf("parsing config %s: %w", path, err)
		}
	}

	// Env var overrides

	// Label config-file-derived credentials so doctor can distinguish
	// "credentials persisted on disk" from "no credentials at all" — without
	// this, users who saved via set-token without an env var see a blank
	// auth_source and can't tell whether their config is being picked up.
	// The label is the literal "config" rather than "config:<path>"; the
	// config file path is exposed separately as report["config_path"], and
	// embedding it in auth_source leaks the user's home directory through
	// doctor's JSON envelope.
	if cfg.AuthSource == "" && (cfg.AuthHeaderVal != "") {
		cfg.AuthSource = "config"
	}

	// Base URL override (used by printing-press verify to point at mock/test servers)
	if v := os.Getenv("DP_GOAT_BASE_URL"); v != "" {
		cfg.BaseURL = v
	}
	if v := os.Getenv("DP_GOAT_BASE_PATH"); v != "" {
		cfg.BasePath = v
	}
	return cfg, nil
}

func (c *Config) AuthHeader() string {
	if c.AuthHeaderVal != "" {
		return c.AuthHeaderVal
	}
	return ""
}

func (c *Config) save() error {
	dir := filepath.Dir(c.Path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("creating config dir: %w", err)
	}
	data, err := toml.Marshal(c)
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}
	return os.WriteFile(c.Path, data, 0o600)
}
