import world from '../../../website/static/map/world.json';
import { mobs, items, type Mob, type Item } from './database';
import { zoneById } from './zones';

// World JSON shapes (generated by website/scripts/parse_world.py from the
// active lib/world files — the same files the server loads).
interface WorldExit { d: string; t: number }
interface WorldRoom { id: number; name: string; desc: string; sector: number; exits: WorldExit[] }
interface WorldZone { id: number; name: string; top: number; rooms: WorldRoom[] }

export interface RoomRecord {
  id: number;
  name: string;
  description: string;
  sector: number;
  zoneId: number;
  zoneName: string;
  exits: Array<{ direction: string; target: number }>;
  mobs: Array<{ vnum: number; name: string; level: number }>;
  items: Array<{ vnum: number; name: string }>;
  shopkeepers: Array<{ vnum: number; name: string; openHours: string }>;
}

const directionName = (code: string) => ({
  n: 'north', e: 'east', s: 'south', w: 'west', u: 'up', d: 'down',
})[code] ?? code;

// Room-level inhabitants: mob spawns keyed by room, item ground/container
// placements keyed by room. Shopkeepers are mobs with a shop at that room.
const mobsByRoom = new Map<number, Array<{ vnum: number; name: string; level: number; shop: Mob['shop'] }>>();
for (const mob of mobs as Mob[]) {
  for (const spawn of mob.spw) {
    if (spawn.room === undefined) continue;
    let list = mobsByRoom.get(spawn.room);
    if (!list) mobsByRoom.set(spawn.room, (list = []));
    list.push({ vnum: mob.v, name: mob.s, level: mob.lvl, shop: mob.shop });
  }
}

const itemsByRoom = new Map<number, Array<{ vnum: number; name: string }>>();
for (const item of items as Item[]) {
  for (const placement of item.rms) {
    if (placement.room === undefined) continue;
    let list = itemsByRoom.get(placement.room);
    if (!list) itemsByRoom.set(placement.room, (list = []));
    list.push({ vnum: item.v, name: item.s });
  }
}

export const rooms: RoomRecord[] = [];
for (const zone of world.zones as WorldZone[]) {
  for (const room of zone.rooms) {
    const inhabitants = mobsByRoom.get(room.id) ?? [];
    rooms.push({
      id: room.id,
      name: room.name,
      description: room.desc,
      sector: room.sector,
      zoneId: zone.id,
      zoneName: zoneById.get(zone.id)?.name ?? `Zone ${zone.id}`,
      exits: room.exits.map((exit) => ({ direction: directionName(exit.d), target: exit.t })),
      mobs: inhabitants.map(({ vnum, name, level }) => ({ vnum, name, level })),
      items: itemsByRoom.get(room.id) ?? [],
      shopkeepers: inhabitants
        .filter((mob) => mob.shop)
        .map((mob) => ({ vnum: mob.vnum, name: mob.name, openHours: mob.shop!.open_hours })),
    });
  }
}

export const roomById = new Map(rooms.map((room) => [room.id, room]));
export const totalRoomCount = rooms.length;
export { directionName };
