import world from '../../../website/static/map/world.json';
import { mobs, items, type Mob, type Item } from './database';

// World JSON shapes (generated by website/scripts/parse_world.py from the
// active lib/world files — the same files the server loads).
interface WorldExit { d: string; t: number }
interface WorldRoom { id: number; name: string; desc: string; sector: number; exits: WorldExit[] }
interface WorldZone { id: number; name: string; top: number; rooms: WorldRoom[] }

export interface ZoneRoom {
  id: number;
  name: string;
  sector: number;
  exitCount: number;
}

export interface ZoneRecord {
  id: number;
  name: string;
  top: number;
  roomCount: number;
  rooms: ZoneRoom[];
  connectedZoneIds: number[];
  mobs: Array<{ vnum: number; name: string; level: number }>;
  items: Array<{ vnum: number; name: string }>;
  shops: Array<{ keeperVnum: number; keeperName: string; openHours: string }>;
}

const worldZones = world.zones as WorldZone[];

const roomZone = new Map<number, number>();
for (const zone of worldZones) {
  for (const room of zone.rooms) roomZone.set(room.id, zone.id);
}

function buildZone(zone: WorldZone): ZoneRecord {
  // Cross-zone exits define connectivity. Only exits landing in a known room
  // count; portals into the void are ignored.
  const connected = new Set<number>();
  for (const room of zone.rooms) {
    for (const exit of room.exits) {
      const targetZone = roomZone.get(exit.t);
      if (targetZone !== undefined && targetZone !== zone.id) connected.add(targetZone);
    }
  }

  const zoneMobs: ZoneRecord['mobs'] = [];
  const zoneMobVnums = new Set<number>();
  for (const mob of mobs as Mob[]) {
    for (const spawn of mob.spw) {
      if (spawn.zone === zone.id || roomZone.get(spawn.room) === zone.id) {
        zoneMobs.push({ vnum: mob.v, name: mob.s, level: mob.lvl });
        zoneMobVnums.add(mob.v);
        break;
      }
    }
  }

  // Items reach a zone three ways: placed in a room/container (rms), carried
  // by a zone mob (mobs), or stocked by a zone shopkeeper (shp).
  const zoneItems: ZoneRecord['items'] = [];
  for (const item of items as Item[]) {
    const placed =
      item.rms.some((p) => p.zone === zone.id || roomZone.get(p.room) === zone.id) ||
      item.mobs.some((carrier) => zoneMobVnums.has(carrier.mob_vnum)) ||
      item.shp.some((stock) => zoneMobVnums.has(stock.keeper_vnum));
    if (placed) zoneItems.push({ vnum: item.v, name: item.s });
  }

  const shops = (mobs as Mob[])
    .filter((mob) => mob.shop && zoneMobVnums.has(mob.v))
    .map((mob) => ({ keeperVnum: mob.v, keeperName: mob.s, openHours: mob.shop!.open_hours }));

  return {
    id: zone.id,
    name: zone.name,
    top: zone.top,
    roomCount: zone.rooms.length,
    rooms: zone.rooms.map((room) => ({
      id: room.id,
      name: room.name,
      sector: room.sector,
      exitCount: room.exits.length,
    })),
    connectedZoneIds: [...connected].sort((a, b) => a - b),
    mobs: zoneMobs,
    items: zoneItems,
    shops,
  };
}

export const zones: ZoneRecord[] = worldZones.map(buildZone);
export const zoneById = new Map(zones.map((zone) => [zone.id, zone]));

// Zone names include design prefixes like "(10-15) Kir Drax'in (Arakon)" —
// the suggested level range, when present, sorts before the bare name.
const nameSortKey = (name: string) => name.replace(/^\((\d+)-(\d+)\)\s*/, (_, lo, hi) => `${String(lo).padStart(2, '0')}-${String(hi).padStart(2, '0')} `);
export const zonesSorted = [...zones].sort((a, b) => nameSortKey(a.name).localeCompare(nameSortKey(b.name)));

export const totalRooms = zones.reduce((sum, zone) => sum + zone.roomCount, 0);

export const sectorName = (value: number) => ({
  0: 'Inside', 1: 'City', 2: 'Field', 3: 'Forest', 4: 'Hills', 5: 'Mountain',
  6: 'Water (swim)', 7: 'Water (no swim)', 8: 'Underwater', 9: 'Flying',
  10: 'Desert', 11: 'Road', 12: 'Lava', 13: 'Ice', 14: 'River', 15: 'Grassland',
})[value] ?? `Sector ${value}`;
