#!/usr/bin/env python3
"""World-data fidelity gate: lib/world must be the C game's data, byte for byte.

The port's world files (rooms, objects, mobs, zones, shops, movement tables)
and its Lua script tree are the C oracle's lib/world and lib/scripts. Nothing
stopped them drifting: in May 2026, 318 Lua script attachments were
keyword-matched onto mobs under an unrelated commit title (DP-1333). This gate
makes any drift fail CI unless it is listed, with a reason, in
docs/fidelity/world-exceptions.tsv.

  check (default)  compare lib/world against docs/fidelity/world-manifest.sha256
  --write          regenerate the manifest from the C oracle checkout
                   (DP_ORACLE_ROOT, default /home/zach/darkpawns-c-oracle)

The manifest is generated, never hand-edited. CI has no C oracle, so it checks
against the committed manifest.
"""

import argparse
import csv
import hashlib
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(REPO, "docs", "fidelity", "world-manifest.sha256")
EXCEPTIONS = os.path.join(REPO, "docs", "fidelity", "world-exceptions.tsv")

# (directory in the C oracle, directory in this repo)
TREES = [
    ("lib/world/mob", "lib/world/mob"),
    ("lib/world/obj", "lib/world/obj"),
    ("lib/world/wld", "lib/world/wld"),
    ("lib/world/zon", "lib/world/zon"),
    ("lib/world/shp", "lib/world/shp"),
    ("lib/world/movesel", "lib/world/movesel"),  # a single file
    ("lib/scripts", "lib/world/scripts"),
]

VALID_KINDS = {"differs", "missing", "extra"}
VALID_STATUS = {"accepted", "pending"}


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def walk(root):
    """Yield file paths under root relative to it, skipping VCS metadata.
    A root that is a single file yields "" (the file itself)."""
    if os.path.isfile(root):
        yield ""
        return
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if d not in (".svn", ".git"))
        for name in sorted(filenames):
            full = os.path.join(dirpath, name)
            yield os.path.relpath(full, root)


def write_manifest(oracle_root):
    lines = []
    for c_dir, repo_dir in TREES:
        src = os.path.join(oracle_root, c_dir)
        if not os.path.exists(src):
            sys.exit(f"world-fidelity: {src} not found; set DP_ORACLE_ROOT")
        for rel in walk(src):
            path = f"{repo_dir}/{rel}" if rel else repo_dir
            lines.append(f"{sha256(os.path.join(src, rel) if rel else src)}  {path}")
    with open(MANIFEST, "w") as f:
        f.write("# Generated by scripts/world_fidelity.py --write from the C oracle.\n")
        f.write("# Do not edit: record intended differences in world-exceptions.tsv.\n")
        f.write("\n".join(lines) + "\n")
    print(f"world-fidelity: wrote {len(lines)} entries to {os.path.relpath(MANIFEST, REPO)}")


def load_manifest():
    expected = {}
    with open(MANIFEST) as f:
        for line in f:
            if not line.strip() or line.startswith("#"):
                continue
            digest, path = line.rstrip("\n").split("  ", 1)
            expected[path] = digest
    return expected


def load_exceptions():
    exceptions = {}
    problems = []
    with open(EXCEPTIONS, newline="") as f:
        rows = [r for r in csv.reader(f, delimiter="\t") if r and not r[0].startswith("#")]
    header, body = rows[0], rows[1:]
    if header != ["path", "kind", "status", "issue", "reason"]:
        problems.append(f"world-exceptions.tsv: unexpected header {header}")
        return exceptions, problems
    for row in body:
        if len(row) != 5 or not row[4].strip():
            problems.append(f"world-exceptions.tsv: row needs 5 non-empty columns: {row}")
            continue
        path, kind, status, issue, reason = row
        if kind not in VALID_KINDS or status not in VALID_STATUS:
            problems.append(f"world-exceptions.tsv: bad kind/status for {path}: {kind}/{status}")
            continue
        exceptions[path] = (kind, status, issue, reason)
    return exceptions, problems


def check():
    expected = load_manifest()
    exceptions, problems = load_exceptions()
    used = set()
    seen = set()

    for path, digest in expected.items():
        full = os.path.join(REPO, path)
        if not os.path.exists(full):
            kind = "missing"
        elif sha256(full) != digest:
            kind = "differs"
        else:
            continue
        exc = exceptions.get(path)
        if exc and exc[0] == kind:
            used.add(path)
        else:
            problems.append(f"{kind}: {path} (C oracle has this file"
                            f"{'' if kind == 'missing' else ' with different bytes'}; "
                            f"restore C's bytes or add an exception with a reason)")

    for _, repo_dir in TREES:
        root = os.path.join(REPO, repo_dir)
        if not os.path.exists(root):
            continue
        for rel in walk(root):
            path = f"{repo_dir}/{rel}" if rel else repo_dir
            seen.add(path)
            if path in expected:
                continue
            exc = exceptions.get(path)
            if exc and exc[0] == "extra":
                used.add(path)
            else:
                problems.append(f"extra: {path} (not in the C oracle; remove it or add an exception with a reason)")

    for path in sorted(set(exceptions) - used):
        problems.append(f"stale exception: {path} no longer differs; delete its row")

    pending = sorted(p for p, e in exceptions.items() if e[1] == "pending" and p in used)
    if problems:
        print("world-fidelity: FAIL")
        for p in problems:
            print("  " + p)
        return 1
    print(f"world-fidelity: OK ({len(expected)} C files; {len(used)} listed exceptions, "
          f"{len(pending)} pending a decision)")
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--write", action="store_true", help="regenerate the manifest from the C oracle")
    args = parser.parse_args()
    if args.write:
        write_manifest(os.environ.get("DP_ORACLE_ROOT", "/home/zach/darkpawns-c-oracle"))
        return 0
    return check()


if __name__ == "__main__":
    sys.exit(main())
