// Code generated from src/interpreter.c cmd_info[] do_action rows; DO NOT EDIT.
// TestSocialMinPositionsMatchCommandGates (pkg/session) checks it against the
// C-derived command_gates.tsv.

package game

// socialMinPosition is each social's minimum_position in C's command table.
// command_interpreter refuses a social below it; for an NPC (lua_action)
// the refusal has no descriptor to reach, so the social simply does not run.
var socialMinPosition = map[string]int{
	"accuse":     6, // POS_SITTING
	"agree":      5, // POS_RESTING
	"apologize":  5, // POS_RESTING
	"applaud":    5, // POS_RESTING
	"anguish":    5, // POS_RESTING
	"bounce":     8, // POS_STANDING
	"bah":        5, // POS_RESTING
	"beckon":     5, // POS_RESTING
	"beg":        5, // POS_RESTING
	"bellow":     5, // POS_RESTING
	"bird":       5, // POS_RESTING
	"bitch":      5, // POS_RESTING
	"blame":      5, // POS_RESTING
	"bleed":      5, // POS_RESTING
	"bless":      5, // POS_RESTING
	"blink":      5, // POS_RESTING
	"blush":      5, // POS_RESTING
	"bonk":       5, // POS_RESTING
	"boink":      5, // POS_RESTING
	"boggle":     5, // POS_RESTING
	"bow":        8, // POS_STANDING
	"brb":        5, // POS_RESTING
	"burp":       5, // POS_RESTING
	"cackle":     5, // POS_RESTING
	"chuckle":    5, // POS_RESTING
	"chide":      5, // POS_RESTING
	"cheer":      5, // POS_RESTING
	"clap":       5, // POS_RESTING
	"comfort":    5, // POS_RESTING
	"comb":       5, // POS_RESTING
	"cough":      5, // POS_RESTING
	"cringe":     5, // POS_RESTING
	"cry":        5, // POS_RESTING
	"cuddle":     5, // POS_RESTING
	"curse":      5, // POS_RESTING
	"curtsey":    8, // POS_STANDING
	"dance":      8, // POS_STANDING
	"daydream":   4, // POS_SLEEPING
	"doh":        5, // POS_RESTING
	"drool":      5, // POS_RESTING
	"embrace":    8, // POS_STANDING
	"fade":       5, // POS_RESTING
	"faint":      5, // POS_RESTING
	"farewell":   5, // POS_RESTING
	"fart":       5, // POS_RESTING
	"flex":       5, // POS_RESTING
	"flip":       8, // POS_STANDING
	"flirt":      5, // POS_RESTING
	"fondle":     5, // POS_RESTING
	"french":     5, // POS_RESTING
	"frown":      5, // POS_RESTING
	"fume":       5, // POS_RESTING
	"fwap":       5, // POS_RESTING
	"gag":        5, // POS_RESTING
	"gasp":       5, // POS_RESTING
	"giggle":     5, // POS_RESTING
	"glare":      5, // POS_RESTING
	"goose":      5, // POS_RESTING
	"greet":      5, // POS_RESTING
	"grin":       5, // POS_RESTING
	"grimace":    5, // POS_RESTING
	"groan":      5, // POS_RESTING
	"grope":      5, // POS_RESTING
	"grovel":     5, // POS_RESTING
	"growl":      5, // POS_RESTING
	"grumble":    5, // POS_RESTING
	"heh":        5, // POS_RESTING
	"hiccup":     5, // POS_RESTING
	"highfive":   5, // POS_RESTING
	"hop":        5, // POS_RESTING
	"howl":       5, // POS_RESTING
	"hug":        5, // POS_RESTING
	"hum":        5, // POS_RESTING
	"hump":       5, // POS_RESTING
	"hush":       5, // POS_RESTING
	"jeer":       5, // POS_RESTING
	"kiss":       5, // POS_RESTING
	"laugh":      5, // POS_RESTING
	"lambada":    8, // POS_STANDING
	"leer":       5, // POS_RESTING
	"listen":     5, // POS_RESTING
	"lick":       5, // POS_RESTING
	"love":       5, // POS_RESTING
	"moan":       5, // POS_RESTING
	"mosh":       5, // POS_RESTING
	"massage":    5, // POS_RESTING
	"muhaha":     5, // POS_RESTING
	"mumble":     5, // POS_RESTING
	"nibble":     5, // POS_RESTING
	"nod":        5, // POS_RESTING
	"noogie":     5, // POS_RESTING
	"nudge":      5, // POS_RESTING
	"nuzzle":     5, // POS_RESTING
	"pace":       5, // POS_RESTING
	"pant":       5, // POS_RESTING
	"pat":        5, // POS_RESTING
	"peer":       5, // POS_RESTING
	"pinch":      5, // POS_RESTING
	"plot":       5, // POS_RESTING
	"piss":       5, // POS_RESTING
	"poke":       5, // POS_RESTING
	"ponder":     5, // POS_RESTING
	"pose":       8, // POS_STANDING
	"pout":       5, // POS_RESTING
	"pray":       6, // POS_SITTING
	"puke":       5, // POS_RESTING
	"punch":      5, // POS_RESTING
	"purr":       5, // POS_RESTING
	"raise":      5, // POS_RESTING
	"reel":       5, // POS_RESTING
	"ren":        5, // POS_RESTING
	"roar":       5, // POS_RESTING
	"rofl":       5, // POS_RESTING
	"ruffle":     8, // POS_STANDING
	"salute":     5, // POS_RESTING
	"scoff":      5, // POS_RESTING
	"scream":     5, // POS_RESTING
	"scratch":    5, // POS_RESTING
	"shame":      5, // POS_RESTING
	"shishkabob": 5, // POS_RESTING
	"shake":      5, // POS_RESTING
	"shiver":     5, // POS_RESTING
	"shrug":      5, // POS_RESTING
	"shudder":    5, // POS_RESTING
	"sigh":       5, // POS_RESTING
	"sing":       5, // POS_RESTING
	"slap":       5, // POS_RESTING
	"smile":      5, // POS_RESTING
	"smell":      5, // POS_RESTING
	"smirk":      5, // POS_RESTING
	"sneeze":     5, // POS_RESTING
	"sneer":      5, // POS_RESTING
	"snicker":    5, // POS_RESTING
	"snap":       5, // POS_RESTING
	"snarl":      5, // POS_RESTING
	"sniff":      5, // POS_RESTING
	"snore":      4, // POS_SLEEPING
	"snowball":   8, // POS_STANDING
	"snuggle":    5, // POS_RESTING
	"spackle":    5, // POS_RESTING
	"spank":      5, // POS_RESTING
	"spew":       5, // POS_RESTING
	"spit":       5, // POS_RESTING
	"squeeze":    5, // POS_RESTING
	"stare":      5, // POS_RESTING
	"startle":    5, // POS_RESTING
	"steam":      5, // POS_RESTING
	"stimpy":     5, // POS_RESTING
	"stretch":    5, // POS_RESTING
	"stroke":     5, // POS_RESTING
	"strut":      8, // POS_STANDING
	"sulk":       5, // POS_RESTING
	"sweat":      5, // POS_RESTING
	"tackle":     5, // POS_RESTING
	"tango":      8, // POS_STANDING
	"tap":        5, // POS_RESTING
	"taunt":      5, // POS_RESTING
	"thank":      5, // POS_RESTING
	"thpbt":      5, // POS_RESTING
	"threaten":   5, // POS_RESTING
	"throttle":   5, // POS_RESTING
	"thumbsup":   5, // POS_RESTING
	"thunk":      5, // POS_RESTING
	"tickle":     5, // POS_RESTING
	"tilt":       5, // POS_RESTING
	"tug":        5, // POS_RESTING
	"twiddle":    5, // POS_RESTING
	"violate":    5, // POS_RESTING
	"waltz":      5, // POS_RESTING
	"wave":       5, // POS_RESTING
	"wedgie":     5, // POS_RESTING
	"wee":        5, // POS_RESTING
	"weep":       5, // POS_RESTING
	"whap":       5, // POS_RESTING
	"whimper":    5, // POS_RESTING
	"whine":      5, // POS_RESTING
	"whistle":    5, // POS_RESTING
	"wiggle":     8, // POS_STANDING
	"wink":       5, // POS_RESTING
	"worship":    5, // POS_RESTING
	"yawn":       5, // POS_RESTING
	"yodel":      5, // POS_RESTING
	"yuball":     5, // POS_RESTING
}

// SocialMinPosition is the social's minimum position in C's command table.
func SocialMinPosition(name string) (int, bool) {
	position, ok := socialMinPosition[name]
	return position, ok
}
