#!/usr/bin/env python3
"""Generate permanent Caddy redirects from Astro's static redirect pages."""

from __future__ import annotations

import html
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DIST = ROOT / "website-astro/dist"
OUTPUT = ROOT / "website/deploy/redirects.caddy"
REFRESH = re.compile(r'<meta http-equiv="refresh" content="0;url=([^"]+)">')


def route_for(path: Path) -> tuple[str, ...]:
    relative = path.relative_to(DIST).as_posix()
    if relative.endswith("/index.html"):
        route = f"/{relative[:-11]}"
        return route, f"{route}/"
    return (f"/{relative}",)


def main() -> None:
    redirects: list[tuple[tuple[str, ...], str]] = []
    for path in sorted(DIST.rglob("*.html")):
        if not path.is_file():
            continue
        match = REFRESH.search(path.read_text(encoding="utf-8"))
        if match:
            redirects.append((route_for(path), html.unescape(match.group(1))))

    lines = ["# Generated by website-astro/scripts/caddy_redirects.py. Do not hand-edit.", ""]
    seen: set[tuple[tuple[str, ...], str]] = set()
    for routes, target in redirects:
        entry = (routes, target)
        if entry in seen:
            continue
        seen.add(entry)
        name = f"legacy_redirect_{len(seen):04d}"
        lines.append(f"@{name} path {' '.join(routes)}")
        lines.append(f"redir @{name} {target} permanent")

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"caddy-redirects: {len(seen)} permanent redirects")


if __name__ == "__main__":
    main()
