package dbmigrate

import (
	"database/sql"
	_ "embed"
	"strings"
	"testing"
)

// The PostgreSQL source schema, frozen at the revision production was converted
// from. It lives in testdata rather than being generated by the runtime because
// the runtime no longer speaks PostgreSQL at all: the conversion tool has to be
// able to prove a historical migration against the schema as it actually was, and
// a fixture that tracked live code could not do that.

//go:embed testdata/pgschema_players.sql
var sourcePlayersSQL string

//go:embed testdata/pgschema_moderation.sql
var sourceModerationSQL string

// applySourceSchema creates the whole PostgreSQL source schema.
func applySourceSchema(t *testing.T, conn *sql.DB) {
	t.Helper()
	applySchemaSQL(t, conn, sourcePlayersSQL)
	applySchemaSQL(t, conn, sourceModerationSQL)
}

// applyPlayersOnlySchema creates only the game-store table, for the tests that
// prove what happens when the source is missing a table the runtime initialises.
func applyPlayersOnlySchema(t *testing.T, conn *sql.DB) {
	t.Helper()
	applySchemaSQL(t, conn, sourcePlayersSQL)
}

// applySchemaSQL runs the statements in one fixture file one at a time, so a
// failure names the statement that failed. Comments and blank lines are dropped.
func applySchemaSQL(t *testing.T, conn *sql.DB, schema string) {
	t.Helper()
	for _, statement := range strings.Split(schema, ";") {
		statement = strings.TrimSpace(statement)
		if statement == "" {
			continue
		}
		var body []string
		for _, line := range strings.Split(statement, "\n") {
			trimmed := strings.TrimSpace(line)
			if trimmed == "" || strings.HasPrefix(trimmed, "--") {
				continue
			}
			body = append(body, line)
		}
		if len(body) == 0 {
			continue
		}
		if _, err := conn.Exec(strings.Join(body, "\n")); err != nil {
			t.Fatalf("apply fixture schema statement %q: %v", firstLine(body), err)
		}
	}
}

func firstLine(lines []string) string {
	if len(lines) == 0 {
		return ""
	}
	line := strings.TrimSpace(lines[0])
	if len(line) > 60 {
		return line[:60] + "..."
	}
	return line
}
