// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"dp-goat-pp-cli/internal/cli"
	"dp-goat-pp-cli/internal/client"
	"dp-goat-pp-cli/internal/config"
	"dp-goat-pp-cli/internal/mcp/cobratree"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("cast_cast",
			mcplib.WithDescription("Cast a spell. Required: spell. Optional: target."),
			mcplib.WithString("spell", mcplib.Required(), mcplib.Description("Spell name")),
			mcplib.WithString("target", mcplib.Description("Spell target (optional)")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/cast", false, []mcpParamBinding{{PublicName: "spell", WireName: "spell", Location: "body"}, {PublicName: "target", WireName: "target", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("consider_consider",
			mcplib.WithDescription("Assess combat difficulty of a target. Required: target."),
			mcplib.WithString("target", mcplib.Required(), mcplib.Description("Target to consider")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/consider", false, []mcpParamBinding{{PublicName: "target", WireName: "target", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("down_down",
			mcplib.WithDescription("Move down."),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/down", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("drink_drink",
			mcplib.WithDescription("Drink from a container. Required: container."),
			mcplib.WithString("container", mcplib.Required(), mcplib.Description("Container to drink from")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/drink", false, []mcpParamBinding{{PublicName: "container", WireName: "container", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("drop_drop",
			mcplib.WithDescription("Drop an item. Required: item."),
			mcplib.WithString("item", mcplib.Required(), mcplib.Description("Item to drop")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/drop", false, []mcpParamBinding{{PublicName: "item", WireName: "item", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("east_east",
			mcplib.WithDescription("Move east."),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/east", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("eat_eat",
			mcplib.WithDescription("Eat food. Required: item."),
			mcplib.WithString("item", mcplib.Required(), mcplib.Description("Food to eat")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/eat", false, []mcpParamBinding{{PublicName: "item", WireName: "item", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("flee_flee",
			mcplib.WithDescription("Attempt to flee from combat. Costs some experience points. May fail if the mob is much faster than you."),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/flee", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("get_get",
			mcplib.WithDescription("Pick up an item from the room or from a container. Use 'get all' to pick up everything. Required: item. Optional: container."),
			mcplib.WithString("container", mcplib.Description("Container to get from (optional)")),
			mcplib.WithString("item", mcplib.Required(), mcplib.Description("Item to pick up")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/get", false, []mcpParamBinding{{PublicName: "container", WireName: "container", Location: "body"}, {PublicName: "item", WireName: "item", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("give_give",
			mcplib.WithDescription("Give an item to someone. Required: item, target."),
			mcplib.WithString("item", mcplib.Required(), mcplib.Description("Item to give")),
			mcplib.WithString("target", mcplib.Required(), mcplib.Description("Recipient (player or mob)")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/give", false, []mcpParamBinding{{PublicName: "item", WireName: "item", Location: "body"}, {PublicName: "target", WireName: "target", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("inventory_inventory",
			mcplib.WithDescription("List carried items."),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/inventory", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("kill_kill",
			mcplib.WithDescription("Initiate combat with a target. Requires a weapon or bare hands. Use 'consider' first to assess difficulty. Required: target."),
			mcplib.WithString("target", mcplib.Required(), mcplib.Description("Target to attack (e.g. 'a blind monk')")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/kill", false, []mcpParamBinding{{PublicName: "target", WireName: "target", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("look_look",
			mcplib.WithDescription("Study your surroundings. Without arguments, shows the room. With a target, examines that target specifically. Optional: target."),
			mcplib.WithString("target", mcplib.Description("Thing to look at (e.g. 'the angel', 'south', 'in the bag')")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/look", false, []mcpParamBinding{{PublicName: "target", WireName: "target", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("north_north",
			mcplib.WithDescription("Move north."),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/north", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("say_say",
			mcplib.WithDescription("Say something to everyone in the room. All players and mobs in the room will see your message. Required: message."),
			mcplib.WithString("message", mcplib.Required(), mcplib.Description("Message to say")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/say", false, []mcpParamBinding{{PublicName: "message", WireName: "message", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("score_score",
			mcplib.WithDescription("Show character stats."),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/score", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("south_south",
			mcplib.WithDescription("Move south."),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/south", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("tell_tell",
			mcplib.WithDescription("Send a private message to another player. Only the target player will see the message, regardless of location. Required: message, target."),
			mcplib.WithString("message", mcplib.Required(), mcplib.Description("Message to send")),
			mcplib.WithString("target", mcplib.Required(), mcplib.Description("Player name")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/tell", false, []mcpParamBinding{{PublicName: "message", WireName: "message", Location: "body"}, {PublicName: "target", WireName: "target", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("up_up",
			mcplib.WithDescription("Move up."),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/up", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("wear_wear",
			mcplib.WithDescription("Equip armor or clothing. Required: item."),
			mcplib.WithString("item", mcplib.Required(), mcplib.Description("Item to wear")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/wear", false, []mcpParamBinding{{PublicName: "item", WireName: "item", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("west_west",
			mcplib.WithDescription("Move west."),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/west", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("who_who",
			mcplib.WithDescription("Show who is online."),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/who", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("wield_wield",
			mcplib.WithDescription("Equip a weapon. Required: item."),
			mcplib.WithString("item", mcplib.Required(), mcplib.Description("Weapon to wield")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/wield", false, []mcpParamBinding{{PublicName: "item", WireName: "item", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("yell_yell",
			mcplib.WithDescription("Shout to the entire zone. Required: message."),
			mcplib.WithString("message", mcplib.Required(), mcplib.Description("Message to yell")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/yell", false, []mcpParamBinding{{PublicName: "message", WireName: "message", Location: "body"}}, []string{}),
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, binaryResponse bool, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		var headers map[string]string
		if binaryResponse {
			headers = map[string]string{client.BinaryResponseHeader: "true"}
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if binaryResponse {
				data, err = c.GetWithHeaders(path, params, headers)
				break
			}
			data, err = c.Get(path, params)
		case "POST":
			if binaryResponse {
				data, _, err = c.PostWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PostWithParams(path, params, bodyArgs)
		case "PUT":
			if binaryResponse {
				data, _, err = c.PutWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PutWithParams(path, params, bodyArgs)
		case "PATCH":
			if binaryResponse {
				data, _, err = c.PatchWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PatchWithParams(path, params, bodyArgs)
		case "DELETE":
			if binaryResponse {
				data, _, err = c.DeleteWithParamsAndHeaders(path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(path, params)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + msg +
					"\nhint: check your API credentials." +
					"\n      Run 'dp-goat-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + msg +
					"\nhint: this API is configured without credentials; the service may be blocking the request by rate limit, geography, bot protection, or endpoint policy." +
					"\n      Run 'dp-goat-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		if binaryResponse {
			out, _ := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      base64.StdEncoding.EncodeToString(data),
				"byte_count":       len(data),
			})
			return mcplib.NewToolResultText(string(out)), nil
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "dp-goat-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "dp-goat-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "dp-goat",
		"description": "Dark Pawns is a MUD (Multi-User Dungeon) with 10,057 rooms, 1,313 mobs, and 854 objects. Commands are sent as JSON...",
		"archetype":   "generic",
		"tool_count":  24,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion dp-goat-pp-cli binary.",
		"resources": []map[string]any{
			{
				"name":        "cast",
				"description": "Manage cast",
				"endpoints":   []string{"cast"},
				"searchable":  true,
			},
			{
				"name":        "consider",
				"description": "Manage consider",
				"endpoints":   []string{"consider"},
				"searchable":  true,
			},
			{
				"name":        "down",
				"description": "Manage down",
				"endpoints":   []string{"down"},
			},
			{
				"name":        "drink",
				"description": "Manage drink",
				"endpoints":   []string{"drink"},
				"searchable":  true,
			},
			{
				"name":        "drop",
				"description": "Manage drop",
				"endpoints":   []string{"drop"},
				"searchable":  true,
			},
			{
				"name":        "east",
				"description": "Manage east",
				"endpoints":   []string{"east"},
			},
			{
				"name":        "eat",
				"description": "Manage eat",
				"endpoints":   []string{"eat"},
				"searchable":  true,
			},
			{
				"name":        "flee",
				"description": "Manage flee",
				"endpoints":   []string{"flee"},
			},
			{
				"name":        "get",
				"description": "Manage get",
				"endpoints":   []string{"get"},
				"searchable":  true,
			},
			{
				"name":        "give",
				"description": "Manage give",
				"endpoints":   []string{"give"},
				"searchable":  true,
			},
			{
				"name":        "inventory",
				"description": "Manage inventory",
				"endpoints":   []string{"inventory"},
			},
			{
				"name":        "kill",
				"description": "Manage kill",
				"endpoints":   []string{"kill"},
				"searchable":  true,
			},
			{
				"name":        "look",
				"description": "Manage look",
				"endpoints":   []string{"look"},
				"searchable":  true,
			},
			{
				"name":        "north",
				"description": "Manage north",
				"endpoints":   []string{"north"},
			},
			{
				"name":        "say",
				"description": "Manage say",
				"endpoints":   []string{"say"},
				"searchable":  true,
			},
			{
				"name":        "score",
				"description": "Manage score",
				"endpoints":   []string{"score"},
			},
			{
				"name":        "south",
				"description": "Manage south",
				"endpoints":   []string{"south"},
			},
			{
				"name":        "tell",
				"description": "Manage tell",
				"endpoints":   []string{"tell"},
				"searchable":  true,
			},
			{
				"name":        "up",
				"description": "Manage up",
				"endpoints":   []string{"up"},
			},
			{
				"name":        "wear",
				"description": "Manage wear",
				"endpoints":   []string{"wear"},
				"searchable":  true,
			},
			{
				"name":        "west",
				"description": "Manage west",
				"endpoints":   []string{"west"},
			},
			{
				"name":        "who",
				"description": "Manage who",
				"endpoints":   []string{"who"},
			},
			{
				"name":        "wield",
				"description": "Manage wield",
				"endpoints":   []string{"wield"},
				"searchable":  true,
			},
			{
				"name":        "yell",
				"description": "Manage yell",
				"endpoints":   []string{"yell"},
				"searchable":  true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
