// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newTellPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyMessage string
	var bodyTarget string

	cmd := &cobra.Command{
		Use:         "tell",
		Short:       "Send a private message to another player. Only the target player will see the message, regardless of location.",
		Long:        "Shortcut for 'tell tell'. Send a private message to another player. Only the target player will see the message, regardless of location.",
		Example:     "  dp-goat-pp-cli tell --message example-value",
		Annotations: map[string]string{"pp:endpoint": "tell.tell", "pp:method": "POST", "pp:path": "/tell"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("message") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "message")
			}
			if !cmd.Flags().Changed("target") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "target")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/tell"
			params := map[string]string{}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyMessage != "" {
				body["message"] = bodyMessage
			}
			if bodyTarget != "" {
				body["target"] = bodyTarget
			}
			data, _, err := c.PostWithParams(path, params, body)

			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyMessage, "message", "", "Message to send")
	cmd.Flags().StringVar(&bodyTarget, "target", "", "Player name")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
