// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newLookPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyTarget string

	cmd := &cobra.Command{
		Use:         "look",
		Short:       "Study your surroundings. Without arguments, shows the room. With a target, examines that target specifically.",
		Long:        "Shortcut for 'look look'. Study your surroundings. Without arguments, shows the room. With a target, examines that target specifically.",
		Example:     "  dp-goat-pp-cli look",
		Annotations: map[string]string{"pp:endpoint": "look.look", "pp:method": "POST", "pp:path": "/look"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/look"
			params := map[string]string{}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyTarget != "" {
				body["target"] = bodyTarget
			}
			data, _, err := c.PostWithParams(path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyTarget, "target", "", "Thing to look at (e.g. 'the angel', 'south', 'in the bag')")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
